[package]
name = "Sudoku"
version = "0.1.0"
authors = ["Cars10 <clawrenz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-integer = "0.1.44"